### ISSUE TITLE
Title of Submit button

### ISSUE THREAD

**Issue by samstickland** [bolshakov/activeadmin-reform#26]
Hi,

Loving this gem, but wondering if anyone has come up with a way to make the buttons use the a different class name rather than the form class name?

I'm using Trailblazer, so the name of the a lot of my admin Reforms is Concept::Contract::Admin, which means all the buttons end up as 'Update Admin', 'Create Admin'.

Having dug into the ActiveAdmin source code a bit I suspect this is going to require an ActiveAdmin option.

**Comment by samstickland** [comment]
https://github.com/activeadmin/activeadmin/issues/4578

**Comment by bolshakov** [comment]
I'm not familiar with Trailblazer. Could you explain what is `Concept::Contract::Admin`?

**Comment by samstickland** [comment]
Oh, it's quite straightforward, it's just a Reform object, which
Trailblazer terms a `Contract`

Trailblazer is a collection of gems written by Nick Sutterer, including
Reform, but using a standardised file layout, with arranged around
'concepts', that live in 'app/concepts'.

Say I have a Concept called Company (used for grouping everything to do
with Company together), then I might have the following layout:

```
  app/
    concepts/
      company/
        cell/              - Directory for Company related cells (see
https://github.com/apotonick/cells)
        contract/
          user.rb       - Reform class for user forms
          admin.rb    - Reform class for admin forms
        etc.
```

Company::Contract::Admin is simply a Reform object, but named using the
Trailblazer layout.

```
class Company::Contract::Admin < Reform::Form
  property :name
  ...
end

```

Hopefully that makes sense!

**Comment by bolshakov** [comment]
I18n translations [should work](https://github.com/bolshakov/activeadmin-reform/blob/master/lib/active_admin/reform/active_record.rb#L32) for Reform forms. 

According to the ActiveAdmin's [ActiveAdmin::Resource::Naming](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource/naming.rb), it takes `resource_label` from resource class name.

**Comment by bolshakov** [comment]
Could you create PR with failing test to reproduce the problem?

**Comment by samstickland** [comment]
Hi,

So after the I18n hint I used I18n-debug to find the key it was looking for
and found that the following fixes my issue:

```
activemodel:
  models:
    company/contract/admin: Company
```

Thanks for your help!

2016-08-15 11:32 GMT+01:00 Tema Bolshakov notifications@github.com:

**Comment by bolshakov** [comment]
Another solution is to specify `model`

``` ruby
class Company::Contract::Admin < Reform::Form
  property :name
  model :company
end
```

Thus, you don't have to provide translations for form.

**Comment by bolshakov** [comment]
See [reform-rails documentation](http://trailblazer.to/gems/reform/#activemodel-compliance) for details

**Comment by samstickland** [comment]
Oh, cool, thanks! I hadn't seen that option :)

S

2016-08-15 13:30 GMT+01:00 Tema Bolshakov notifications@github.com:
