### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by timoschilling** [bolshakov/activeadmin-reform#3]
What do you think? I think it should be named `activeadmin-reform` / `ActiveAdmin::Reform` (sure the right name should be `active_admin-reform` but thats not in harmony with `activeadmin`)
http://guides.rubygems.org/name-your-gem/

**Comment by bolshakov** [comment]
I've never seen this guide before. This make sense for me. I like `activeadmin-reform`

**Comment by bolshakov** [comment]
@timoschilling Thank you for review!
