### ISSUE TITLE
UnfilteredParameters exception with rails 5.1.4

### ISSUE THREAD

**Issue by adrienbourgeois** [bolshakov/activeadmin-reform#30]
I've upgraded rails from 4.2 to 5.1.4 and the activeadmin pages that use activeadmin-reform now throw this error

```
Completed 500 Internal Server Error in 2213ms (ActiveRecord: 21.0ms)



ActionController::UnfilteredParameters - unable to convert unpermitted parameters to hash:

::1 - - [09/Jan/2018:12:15:19 AEDT] "GET /admin/users HTTP/1.1" 500 192394
http://localhost:3000/admin/mag_sections -> /admin/users
Started POST "/__better_errors/0e4fdaae42ae6f5e/variables" for ::1 at 2018-01-09 12:15:22 +1100
  User Load (0.7ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" desc LIMIT $1  [["LIMIT", 11]]
  User Load (0.7ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" desc LIMIT $1 OFFSET $2  [["LIMIT", 11], ["OFFSET", 0]]
::1 - - [09/Jan/2018:12:15:22 AEDT] "POST /__better_errors/0e4fdaae42ae6f5e/variables HTTP/1.1" 200 3838
http://localhost:3000/admin/users -> /__better_errors/0e4fdaae42ae6f5e/variables
```

### Reform version
2.2.4

### ActiveAdmin version
1.0.0.pre4

### ActiveAdmin::Reform version
0.4.0

**Comment by bolshakov** [comment]
@adrienbourgeois thanks for report!
Unfortunately it doesn't work on Rails >= 5 yet. See https://travis-ci.org/bolshakov/activeadmin-reform
It worth mentioning in gemspec to avoid confusion.

**Comment by adrienbourgeois** [comment]
Thanks @bolshakov , keep us updated :)

**Comment by mslade-fairfax** [comment]
Hi, we've created a branch with changes that have our project working with rails 5:

https://github.com/mslade-fairfax/activeadmin-reform/tree/ffx-rails5

It works by circumventing rails 5 strong parameters, by passing everything through reform's `#validate`.
A couple of old methods were re-instated to make it work.
For all I know this breaks other versions of rails, but we're letting people see the changes anyway, in case it helps.

**Comment by mslade-fairfax** [comment]
So it appears the above link to the CI thinks everything works with rails 5 now.  Which means I don't know why we needed to make changes to the gem to get it to work.

**Comment by faucct** [comment]
Hello. I see two changes in your fork:

- Rails requirement should allow version 5
- `DataAccess` changes

Here is a pull request making Rails 5 supported: it was only enough to remove version constraints there.
https://github.com/bolshakov/activeadmin-reform/pull/37
The specs you have seen on Travis CI were run in this branch.

**Comment by bolshakov** [comment]
Version 0.6.0 with rails 5 support published!
