### ISSUE TITLE
Multiple form objects for 1 resource

### ISSUE THREAD

**Issue by panSarin** [bolshakov/activeadmin-reform#33]
Is there any option to specify multiple forms for 1 resource ?

**Comment by bolshakov** [comment]
@panSarin no, it's impossible to wrap the same object into several forms. Probably it's possible to create form, which reuse other forms.

@faucct reform guru, do you know something about reusing forms?

**Comment by faucct** [comment]
@panSarin Could you give us an example? If you are talking about wrapping an object in multiple forms like middlewares, then you could implement that inside your form class, though I don't think that there is a single official way to do this with Reform.

**Comment by bolshakov** [comment]
@panSarin feel free to reopen this issue if you have something to add
