### ISSUE TITLE
Not compatible with active admin 2.1.0

### ISSUE THREAD

**Issue by joshudev** [bolshakov/activeadmin-reform#40]
Hi @bolshakov,

Is it possible to use ActiveAdmin-Reform with ActiveAdmin 2.1.0?

The gemspec specifies:

`spec.add_dependency 'activeadmin', ['>= 1.2.1', '<= 2.0.0.alpha']`

There are some useful updates in ActiveAdmin 2 - especially the performance related fixes in 2.1.0, so would be good to be able to use it if possible.

Many thanks in advance.

**Comment by bolshakov** [comment]
Hi, @joshudev I've just published activeadmin-reform 1.1.0 with relaxed ActiveAdmin requirements. I added an automated test build against ActiveAdmin 2.1.0, but haven't a chance to test it in a real app.

Let me know if you find any issues.
